kind = "web"
previewPath = "/"
title = "Fire Kaki"
version = "1.0.0"
id = "artifacts/fire-kaki"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19120

[services.development]
run = "pnpm --filter @workspace/fire-kaki run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fire-kaki", "run", "build" ]
publicDir = "artifacts/fire-kaki/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19120"
BASE_PATH = "/"
