#!/usr/bin/env sh
# Mirror AGENTS.md → replit.md. AGENTS.md is the master.
# Idempotent: rerunning produces the same output.
set -e
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"
if [ ! -f AGENTS.md ]; then
  echo "AGENTS.md not found at repo root" >&2
  exit 1
fi
{
  printf '%s\n' '<!-- AUTO-GENERATED FROM AGENTS.md — DO NOT EDIT THIS FILE DIRECTLY.'
  printf '%s\n' '     The pre-commit hook and scripts/post-merge.sh keep this file in sync'
  printf '%s\n' '     with AGENTS.md. To change content, edit AGENTS.md. -->'
  printf '\n'
  cat AGENTS.md
} > replit.md.tmp
mv replit.md.tmp replit.md
